In [41]:
import requests  #to query the API 
import re  #regular expressions
import pandas as pd   # for dataframes
import json

import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB


In [42]:
df = pd.read_csv("topHL_LEMM_DF.csv", index_col=0).dropna()
df

abbott  abortion  abuse  abusing  abusive  academy  access  accomplishe  \
0         0         0      0        0        0        0       0            0   
1         0         0      0        0        0        0       0            0   
2         0         0      0        0        0        0       0            0   
3         0         0      0        0        0        0       0            0   
4         0         0      0        0        0        0       0            0   
..      ...       ...    ...      ...      ...      ...     ...          ...   
269       0         0      0        0        0        0       0            0   
270       0         0      0        0        0        0       0            0   
271       0         0      0        0        0        0       0            0   
272       0         0      0        0        0        0       0            0   
273       0         0      0        0        0        0       0            0   

     according  account  ...  worked  worker  world  writer  wyoming  year  \
0            0        0  ...       0       0      0       0        0     0   
1            0        0  ...       0       0      0       0        0     0   
2            0        0  ...       0       0      0       0        0     0   
3            0        0  ...       0       0      0       0        0     0   
4            0        0  ...       0       0      0       0        0     0   
..         ...      ...  ...     ...     ...    ...     ...      ...   ...   
269          0        0  ...       0       0      0       0        0     0   
270          0        0  ...       0       0      0       0        0     0   
271          0        0  ...       0       0      0       0        0     0   
272          0        0  ...       0       0      0       0        0     0   
273          0        0  ...       0       0      0       0        0     0   

     york  young  youth          Source  
0       0      0      0        abc-news  
1       0      0      0        abc-news  
2       0      0      0        abc-news  
3       1      0      0        abc-news  
4       1      0      0        abc-news  
..    ...    ...    ...             ...  
269     0      0      0    advocate.com  
270     0      0      0    advocate.com  
271     0      0      0        nbc-news  
272     0      0      0    advocate.com  
273     0      0      0  breitbart-news  

[273 rows x 1430 columns]

In [43]:
df['Source'] = df['Source'].str.replace(',', '')
df['Source'] = df['Source'].str.replace('-', '')
df['Source'] = df['Source'].str.replace('.', '')
df['Source'] = df['Source'].astype('string')
#df['Volume'] = pd.to_numeric(df['Source'], errors='coerce')

/tmp/ipykernel_129/3588509770.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Source'] = df['Source'].str.replace('.', '')


In [44]:
df['Source'] = df['Source'].astype('string')
df['Source']

0            abcnews
1            abcnews
2            abcnews
3            abcnews
4            abcnews
           ...      
269      advocatecom
270      advocatecom
271          nbcnews
272      advocatecom
273    breitbartnews
Name: Source, Length: 273, dtype: string

In [45]:
df.to_csv("Source_HL_clean.csv")

In [5]:
sample_df = df.groupby("Source").sample(n=6, random_state=1)
sample_df

abbott  abortion  abuse  abusing  abusive  academy  access  accomplishe  \
40        0         0      0        0        0        0       0            0   
31        0         0      0        0        0        0       0            0   
46        0         0      0        0        0        0       0            0   
65        0         0      0        0        0        0       0            0   
191       0         0      0        0        0        0       0            0   
49        0         0      0        0        0        0       0            0   
131       0         0      0        0        0        0       0            0   
255       0         0      0        0        0        0       0            0   
211       0         0      0        0        0        0       0            0   
147       0         0      0        0        0        0       0            0   
257       0         0      0        0        0        0       0            0   
178       0         0      0        0        0        0       0            0   
148       0         0      0        0        0        0       0            0   
146       0         0      0        0        0        0       0            0   
273       0         0      0        0        0        0       0            0   
152       0         0      0        0        0        0       0            0   
259       0         0      0        0        0        0       0            0   
169       0         0      0        0        0        0       0            0   
94        0         0      0        0        0        0       0            0   
97        0         0      0        0        0        0       0            0   
74        0         0      0        0        0        0       0            0   
101       0         0      0        0        0        0       0            0   
93        0         0      0        0        0        0       0            0   
106       0         0      0        0        0        0       0            0   
248       0         0      0        0        0        0       0            0   
167       0         0      0        0        0        0       0            0   
154       0         0      0        0        0        0       0            0   
180       0         0      0        0        0        0       0            0   
216       0         0      0        0        0        0       0            0   
215       0         1      0        0        0        0       0            0   
228       0         0      0        0        0        0       0            0   
212       0         0      0        0        0        0       0            0   
193       0         0      0        0        0        0       0            0   
163       0         0      0        0        0        0       0            0   
125       0         0      0        0        0        0       0            0   
166       0         0      0        0        0        0       0            0   
205       0         0      0        0        0        0       0            0   
258       0         0      0        0        0        0       0            0   
213       0         0      0        0        0        0       0            0   
133       0         0      0        0        0        0       0            0   
189       0         0      0        0        0        0       0            0   
222       0         0      0        0        0        0       0            0   

     according  account  ...  worked  worker  world  writer  wyoming  year  \
40           0        0  ...       0       0      0       0        0     0   
31           0        0  ...       0       0      0       0        0     0   
46           0        0  ...       0       0      0       0        0     0   
65           0        0  ...       0       0      0       0        0     1   
191          0        0  ...       0       0      0       0        0     0   
49           0        0  ...       0       0      0       0        0     0   
131          0    

In [6]:
sample_df['Source'] = sample_df['Source'].astype("string")
type(sample_df["Source"])

pandas.core.series.Series

In [7]:
sample_df.dtypes

abbott       int64
abortion     int64
abuse        int64
abusing      int64
abusive      int64
             ...  
year         int64
york         int64
young        int64
youth        int64
Source      string
Length: 1430, dtype: object

In [15]:
#traindf_nolabels (x_train)
x_train = sample_df.drop(columns = 'Source')
#train_labels (y_train)
y_train = sample_df.Source

In [16]:
#testdf_nolabels (x_test)
x_test = df.drop(sample_df.index).drop(columns = 'Source')

#testdf_withlabels?
#x = df.drop(sample_df.index)

#testdf_labels (y_test)
y_test = df.drop(sample_df.index).Source.to_numpy()

In [19]:
MyModelNB= MultinomialNB()
## When you look up this model, you learn that it wants the 
## !!! DF separate from the labels  !!!
MyModelNB.fit(x_train, y_train)
y_pred = MyModelNB.predict(x_test)


In [20]:
y_pred

array(['abcnews', 'nbcnews', 'nbcnews', 'abcnews', 'abcnews',
       'breitbartnews', 'breitbartnews', 'abcnews', 'advocatecom',
       'advocatecom', 'nbcnews', 'nbcnews', 'nbcnews', 'nbcnews',
       'nbcnews', 'abcnews', 'abcnews', 'nbcnews', 'nbcnews',
       'minneapolis star tribune', 'nbcnews', 'nbcnews',
       'minneapolis star tribune', 'minneapolis star tribune', 'abcnews',
       'abcnews', 'abcnews', 'nbcnews', 'nbcnews', 'nbcnews', 'nbcnews',
       'abcnews', 'breitbartnews', 'the daily caller',
       'minneapolis star tribune', 'the daily caller', 'the daily caller',
       'advocatecom', 'minneapolis star tribune', 'abcnews',
       'advocatecom', 'abcnews', 'abcnews', 'abcnews', 'abcnews',
       'abcnews', 'minneapolis star tribune', 'minneapolis star tribune',
       'minneapolis star tribune', 'abcnews', 'abcnews', 'nbcnews',
       'the daily caller', 'nbcnews', 'minneapolis star tribune',
       'nbcnews', 'abcnews', 'nbcnews', 'nbcnews', 'nbcnews', 'nbcnews',
 

In [22]:
## confusion matrix
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
print("\nThe confusion matrix is:")
print(cnf_matrix)
print(MyModelNB.predict_proba(x_test))


The confusion matrix is:
[[32  9  5  0 12 27  4]
 [ 9  8  6  1  4  6  1]
 [ 5  0  2  2  2  1  1]
 [10  8  4  0  9  8  1]
 [ 5  2  4  1  5  2  1]
 [ 2  2  3  2  0  7  3]
 [ 3  1  1  0  3  6  1]]
[[0.38280881 0.1257777  0.02582993 ... 0.08325052 0.30995226 0.06825263]
 [0.05998704 0.11794859 0.17907833 ... 0.1559329  0.43484953 0.02826105]
 [0.15200584 0.00233499 0.0021271  ... 0.08334786 0.58767959 0.16112901]
 ...
 [0.29378102 0.08219673 0.21985258 ... 0.12201121 0.06037075 0.11701594]
 [0.1045114  0.17567686 0.05915846 ... 0.13047096 0.34452712 0.16727559]
 [0.07275693 0.07162234 0.06571512 ... 0.07106225 0.56405518 0.06886886]]


In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                          precision    recall  f1-score   support

                 abcnews       0.48      0.36      0.41        89
             advocatecom       0.27      0.23      0.25        35
           breitbartnews       0.08      0.15      0.11        13
                 foxnews       0.00      0.00      0.00        40
minneapolis star tribune       0.14      0.25      0.18        20
                 nbcnews       0.12      0.37      0.18        19
        the daily caller       0.08      0.07      0.07        15

                accuracy                           0.24       231
               macro avg       0.17      0.20      0.17       231
            weighted avg       0.26      0.24      0.24       231



In [27]:
abc_df = df.loc[df["Source"] == "abcnews"]
fox_df = df.loc[df["Source"] == "foxnews"]
ad_df = df.loc[df["Source"] == "advocatecom"]
mst_df = df.loc[df["Source"] == "minneapolis star tribune"]
nbc_df =df.loc[df["Source"] == "nbcnews"]
tdc_df = df.loc[df["Source"] == "the daily caller"]
b_df = df.loc[df["Source"] == "breitbartnews"]

In [28]:
X1, y1 = abc_df.drop(columns = 'Source'), abc_df['Source']
X2, y2 = fox_df.drop(columns = 'Source'), fox_df['Source']
X3, y3 = ad_df.drop(columns = 'Source'), ad_df['Source']
X4, y4 = mst_df.drop(columns = 'Source'), mst_df['Source']
X5, y5 = nbc_df.drop(columns = 'Source'), nbc_df['Source']
X6, y6 = tdc_df.drop(columns = 'Source'), tdc_df['Source']
X7, y7 = b_df.drop(columns = 'Source'), b_df['Source']

In [30]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.7, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.7, random_state=42)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.7, random_state=42)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.7, random_state=42)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.7, random_state=42)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.7, random_state=42)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.7, random_state=42)


In [33]:
X_train = pd.concat([X_train1, X_train2, X_train3, X_train4, X_train5, X_train6, X_train7])

In [35]:
X_test = pd.concat([X_test1, X_test2, X_test3, X_test4, X_test5, X_test6, X_test7])

In [36]:
y_train = pd.concat([y_train1, y_train2, y_train3, y_train4, y_train5, y_train6, y_train7])
y_test = pd.concat([y_test1, y_test2, y_test3, y_test4, y_test5, y_test6, y_test7])

In [37]:
MyModelNB= MultinomialNB()
## When you look up this model, you learn that it wants the 
## !!! DF separate from the labels  !!!
MyModelNB.fit(X_train, y_train)
y_pred = MyModelNB.predict(X_test)


In [38]:
y_pred

array(['abcnews', 'abcnews', 'abcnews', 'advocatecom', 'abcnews',
       'abcnews', 'abcnews', 'advocatecom', 'abcnews', 'abcnews',
       'abcnews', 'abcnews', 'abcnews', 'minneapolis star tribune',
       'abcnews', 'minneapolis star tribune', 'abcnews', 'abcnews',
       'the daily caller', 'advocatecom', 'abcnews', 'nbcnews', 'abcnews',
       'abcnews', 'abcnews', 'abcnews', 'abcnews', 'abcnews', 'abcnews',
       'abcnews', 'abcnews', 'minneapolis star tribune', 'advocatecom',
       'foxnews', 'abcnews', 'abcnews', 'abcnews', 'abcnews', 'abcnews',
       'abcnews', 'breitbartnews', 'abcnews', 'abcnews', 'abcnews',
       'abcnews', 'abcnews', 'abcnews', 'abcnews', 'foxnews', 'abcnews',
       'abcnews', 'foxnews', 'abcnews', 'advocatecom', 'abcnews',
       'abcnews', 'advocatecom', 'abcnews', 'abcnews', 'breitbartnews',
       'minneapolis star tribune', 'abcnews', 'foxnews',
       'minneapolis star tribune', 'minneapolis star tribune', 'abcnews',
       'nbcnews', 'advocateco

In [39]:
## confusion matrix
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
print("\nThe confusion matrix is:")
print(cnf_matrix)
print(MyModelNB.predict_proba(X_test))


The confusion matrix is:
[[46  6  2  4  6  2  1]
 [14  6  0  4  4  0  1]
 [ 4  5  0  2  1  1  1]
 [17  2  1  5  5  0  3]
 [11  4  0  2  1  0  1]
 [ 9  3  0  1  2  2  1]
 [10  2  0  2  0  0  1]]
[[9.81009296e-01 9.32428585e-03 7.15023460e-03 ... 3.34236319e-04
  8.72892817e-05 2.01541177e-04]
 [9.99596662e-01 4.02725994e-04 2.47100077e-08 ... 6.63575877e-08
  8.53244589e-09 8.86756097e-09]
 [9.58964887e-01 7.59362557e-03 3.29647872e-04 ... 8.33784105e-04
  2.15525174e-04 2.31975822e-04]
 ...
 [1.02141974e-01 4.65153721e-01 5.81373241e-03 ... 1.30182737e-02
  3.66397321e-02 2.72210311e-01]
 [6.07281047e-01 1.30036231e-01 1.14968065e-02 ... 1.43157673e-01
  7.34415534e-02 1.25001207e-02]
 [2.48614371e-02 9.07032181e-01 2.92583783e-03 ... 3.92068308e-03
  5.43295743e-03 1.81683863e-02]]


In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                          precision    recall  f1-score   support

                 abcnews       0.41      0.69      0.52        67
             advocatecom       0.21      0.21      0.21        29
           breitbartnews       0.00      0.00      0.00        14
                 foxnews       0.25      0.15      0.19        33
minneapolis star tribune       0.05      0.05      0.05        19
                 nbcnews       0.40      0.11      0.17        18
        the daily caller       0.11      0.07      0.08        15

                accuracy                           0.31       195
               macro avg       0.21      0.18      0.18       195
            weighted avg       0.27      0.31      0.27       195

